# Generated by Django 5.0.2 on 2025-02-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('source_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('translated_text', models.TextField()),
                ('model', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_count', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['source_text', 'source_language', 'target_language', 'model', 'mode'], name='core_transl_source__502a56_idx')],
            },
        ),
    ]
