# Generated by Django 5.0.2 on 2025-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTranslationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100)),
                ('original_term', models.CharField(max_length=255)),
                ('translated_term', models.CharField(max_length=255)),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Group Translation Memories',
                'indexes': [models.Index(fields=['group_id'], name='core_groupt_group_i_c7c826_idx'), models.Index(fields=['original_term'], name='core_groupt_origina_618101_idx')],
                'unique_together': {('group_id', 'original_term', 'source_language', 'target_language')},
            },
        ),
    ]
