# Generated by Django 5.0.2 on 2025-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grouptranslationmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextualTranslationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('context_hash', models.CharField(max_length=255)),
                ('context_summary', models.TextField(blank=True)),
                ('topic_category', models.CharField(blank=True, max_length=100)),
                ('entities_involved', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['context_hash'], name='core_contex_context_a53501_idx'), models.Index(fields=['topic_category'], name='core_contex_topic_c_e138ac_idx'), models.Index(fields=['source_language', 'target_language'], name='core_contex_source__0db9d8_idx')],
                'unique_together': {('source_text', 'source_language', 'target_language', 'context_hash')},
            },
        ),
        migrations.CreateModel(
            name='ConversationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('topic_category', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('keywords', models.JSONField(default=list)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'topic_category'], name='core_conver_session_8b910b_idx')],
                'unique_together': {('session_id', 'topic_category', 'start_timestamp')},
            },
        ),
        migrations.CreateModel(
            name='EntityTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_context', models.TextField(blank=True)),
                ('first_mentioned', models.DateTimeField(auto_now_add=True)),
                ('last_mentioned', models.DateTimeField(auto_now=True)),
                ('mention_count', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'entity_type'], name='core_entity_session_85168d_idx'), models.Index(fields=['entity_name'], name='core_entity_entity__2b0700_idx')],
                'unique_together': {('session_id', 'entity_type', 'entity_name')},
            },
        ),
        migrations.CreateModel(
            name='MessageCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('cluster_id', models.CharField(max_length=100)),
                ('message_ids', models.JSONField(default=list)),
                ('cluster_type', models.CharField(max_length=50)),
                ('cluster_summary', models.TextField(blank=True)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('coherence_score', models.FloatField(default=0.5)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='core_messag_session_13c154_idx'), models.Index(fields=['cluster_type'], name='core_messag_cluster_9dde32_idx')],
                'unique_together': {('session_id', 'cluster_id')},
            },
        ),
        migrations.CreateModel(
            name='TranslationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('original_text', models.TextField()),
                ('original_translation', models.TextField()),
                ('corrected_translation', models.TextField()),
                ('source_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('context_provided', models.TextField(blank=True)),
                ('feedback_type', models.CharField(max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='core_transl_user_id_d35b68_idx'), models.Index(fields=['session_id'], name='core_transl_session_31b1ca_idx'), models.Index(fields=['feedback_type'], name='core_transl_feedbac_5f3849_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTranslationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('preferred_formality', models.CharField(default='casual', max_length=20)),
                ('domains_of_interest', models.JSONField(default=list)),
                ('personal_glossary', models.JSONField(default=dict)),
                ('language_pairs', models.JSONField(default=dict)),
                ('style_preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='core_usertr_user_id_a471af_idx')],
            },
        ),
    ]
