# Generated by Django 5.0.2 on 2025-09-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contextualtranslationmemory_conversationtopic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupTranslationMemory',
        ),
    ]
