# Generated by Django 5.0.2 on 2025-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_grouptranslationmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('input_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('output_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['model_name', 'request_timestamp'], name='core_apiusa_model_n_b3565b_idx'), models.Index(fields=['request_timestamp'], name='core_apiusa_request_d20669_idx'), models.Index(fields=['user_id'], name='core_apiusa_user_id_4f3e44_idx')],
            },
        ),
    ]
